export const pairingPage = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pair Joypad Air</title>
<style>.top{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.top label{font-size:14px;white-space:nowrap}select{font:inherit;min-height:44px;border:1px solid #bbb;border-radius:10px;padding:8px;background:white}button:disabled{opacity:.5;cursor:wait}*{box-sizing:border-box}body{margin:0;background:#f5f5f7;color:#1d1d1f;font:17px/1.5 -apple-system,BlinkMacSystemFont,sans-serif}main{max-width:820px;margin:48px auto;padding:0 24px}h1{font-size:36px;letter-spacing:-1px;line-height:1.15;margin:12px 0}h2{font-size:20px}p{color:#5a5a60}.card{background:white;border-radius:24px;padding:28px;margin:24px 0}.pair{display:grid;grid-template-columns:280px 1fr;gap:28px;align-items:center}img{width:100%;height:auto;display:block}button{font:inherit;border:0;border-radius:24px;padding:12px 20px;background:#0071e3;color:white;cursor:pointer;min-height:44px}button.secondary{background:#ececf0;color:#1d1d1f}button:focus-visible,textarea:focus-visible{outline:3px solid #0071e3;outline-offset:3px}textarea{font:12px/1.5 monospace;width:100%;min-height:110px;margin-top:16px;border:1px solid #aaa;border-radius:12px;padding:12px}.device{display:flex;justify-content:space-between;align-items:center;gap:16px;border-top:1px solid #eee;padding:16px 0}.muted{font-size:14px;color:#62626a}.actions{display:flex;gap:10px;flex-wrap:wrap}#error{color:#b32920}@media(max-width:650px){main{margin:24px auto}.pair{grid-template-columns:1fr}.pair img{max-width:300px;margin:auto}}</style>
<main><div class="top"><p class="muted" data-i18n="tag">JOYPAD AIR · LOCAL PAIRING</p><label><span data-i18n="language">Language</span> <select id="language"><option value="en">English</option><option value="es">Español</option></select></label></div><h1 data-i18n="title">Connect your iPhone.</h1><p id="mac" data-loading>Loading this Mac…</p><section class="card pair"><img id="qr" alt="One-time pairing QR code" width="420" height="420"><div><h2 data-i18n="scan">Scan once. Remember your Mac.</h2><p data-i18n="instructions">In Joypad Air, choose Pair a Mac → Scan Mac QR code. Review this Mac’s name, then pair.</p><p class="muted" id="expiry"></p><div class="actions"><button id="copy" data-i18n="copy">Copy pairing text</button><button class="secondary" id="renew" data-i18n="renew">New QR code</button></div><p id="feedback" class="muted" role="status"></p><details><summary data-i18n="manual">Use pairing text instead</summary><textarea id="payload" readonly aria-label="Pairing text"></textarea></details></div></section><p id="error" role="alert"></p><section class="card"><h2 data-i18n="devices">Paired phones</h2><div id="devices"></div></section><p class="muted" data-i18n="privacy">Pairing stays on this network. The QR confirms this Mac's identity; your saved connection uses encryption. Keep this page on your Mac.</p></main>
<script>
const strings={"en": {"tag": "JOYPAD AIR · LOCAL PAIRING", "title": "Connect your iPhone.", "loading": "Loading this Mac…", "scan": "Scan once. Remember your Mac.", "instructions": "In Joypad Air, choose Pair a Mac → Scan Mac QR code. Review this Mac’s name, then pair.", "copy": "Copy pairing text", "renew": "New QR code", "manual": "Use pairing text instead", "devices": "Paired phones", "privacy": "Pairing stays on this network. The QR confirms this Mac’s identity; your saved connection uses encryption. Keep this page on your Mac.", "language": "Language", "empty": "No phones paired yet.", "connected": "Connected", "saved": "Saved", "remove": "Remove", "expires": "QR code expires", "copied": "Copied. Paste this in Joypad Air on your iPhone.", "selectCopy": "Select and copy the pairing text below.", "readError": "Could not read pairing status.", "updateError": "Could not update pairing.", "qrAlt": "One-time pairing QR code", "payloadLabel": "Pairing text"}, "es": {"tag": "JOYPAD AIR · EMPAREJAMIENTO LOCAL", "title": "Conecta tu iPhone.", "loading": "Cargando este Mac…", "scan": "Escanea una vez. Recuerda tu Mac.", "instructions": "En Joypad Air, elige Pair a Mac → Scan Mac QR code. Revisa el nombre de este Mac y confirma.", "copy": "Copiar texto de conexión", "renew": "Nuevo código QR", "manual": "Usar texto de conexión", "devices": "Teléfonos emparejados", "privacy": "El emparejamiento permanece en esta red. El QR confirma la identidad del Mac; la conexión guardada usa cifrado. Mantén esta página en tu Mac.", "language": "Idioma", "empty": "Todavía no hay teléfonos emparejados.", "connected": "Conectado", "saved": "Guardado", "remove": "Eliminar", "expires": "El código QR vence a las", "copied": "Copiado. Pégalo en Joypad Air en tu iPhone.", "selectCopy": "Selecciona y copia el texto que aparece abajo.", "readError": "No se pudo leer el estado del emparejamiento.", "updateError": "No se pudo actualizar el emparejamiento.", "qrAlt": "Código QR de un solo uso", "payloadLabel": "Texto de conexión"}};
let language='en',state,requestID=0;
try{language=localStorage.getItem('joypad-air-language')||navigator.language||'en'}catch{language=navigator.language||'en'}
language=new URL(location.href).searchParams.get('lang')||language;
language=/^es/i.test(language)?'es':'en';
const text=key=>strings[language][key];
function render(){
 document.documentElement.lang=language;document.title=text('title');document.getElementById('language').value=language;
 document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=text(e.dataset.i18n));
 document.getElementById('qr').alt=text('qrAlt');document.getElementById('payload').setAttribute('aria-label',text('payloadLabel'));
 if(!state){document.getElementById('mac').textContent=text('loading');return}
 document.getElementById('mac').textContent=state.name;document.getElementById('qr').src=state.qr;document.getElementById('payload').value=state.invitation;
 document.getElementById('expiry').textContent=text('expires')+' '+new Date(state.expiresAt).toLocaleTimeString(language);
 const list=document.getElementById('devices');list.replaceChildren();if(!state.paired.length)list.textContent=text('empty');
 for(const p of state.paired){const row=document.createElement('div');row.className='device';const label=document.createElement('span');label.textContent=p.name+' · '+text(p.connected?'connected':'saved');const b=document.createElement('button');b.className='secondary';b.textContent=text('remove');b.onclick=()=>mutate('/api/revoke',{id:p.id},b);row.append(label,b);list.append(row)}
}
async function refresh(){const id=++requestID;try{const r=await fetch('/api/state');if(!r.ok)throw Error(text('readError'));const next=await r.json();if(id!==requestID)return;state=next;render();document.getElementById('error').textContent=''}catch(e){if(id===requestID)document.getElementById('error').textContent=e.message}}
async function mutate(url,body={},button){if(button)button.disabled=true;try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-joypad-pairing':'1'},body:JSON.stringify(body)});if(!r.ok)throw Error(text('updateError'));await refresh()}catch(e){document.getElementById('error').textContent=e.message}finally{if(button)button.disabled=false}}
document.getElementById('language').onchange=e=>{language=e.target.value;const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);try{localStorage.setItem('joypad-air-language',language)}catch{}document.getElementById('feedback').textContent='';render()};
document.getElementById('copy').onclick=async()=>{if(!state)return;try{await navigator.clipboard.writeText(state.invitation);document.getElementById('feedback').textContent=text('copied')}catch{document.getElementById('payload').closest('details').open=true;document.getElementById('payload').select();document.getElementById('feedback').textContent=text('selectCopy')}};
document.getElementById('renew').onclick=e=>mutate('/api/renew',{},e.target);render();refresh();setInterval(refresh,5000);
</script></html>`;
